CREATE TABLE IF NOT EXISTS DailyQARecord (
    id integer PRIMARY KEY,
    therapist TEXT NOT NULL,
    createDate timestamp NOT NULL,
    room TEXT NOT NULL,
    doorWarning TEXT NOT NULL,
    doorInterlock TEXT NOT NULL,
    intercom TEXT NOT NULL,
    videoMonitor TEXT NOT NULL,
    searchButton TEXT NOT NULL,
    radiationMonitor TEXT NOT NULL,
    beamPause TEXT NOT NULL,
    collisionInterlock TEXT NOT NULL,
    beamOnIndicator TEXT NOT NULL,
    xrayOnIndicator TEXT NOT NULL,
    safetyCheck TEXT NOT NULL,
    panelA TEXT NOT NULL,
    panelB TEXT NOT NULL,
    CBCTA TEXT NOT NULL,
    CBCTB TEXT NOT NULL,
    imageCheck TEXT NOT NULL,
    laserSI TEXT NOT NULL,
    laserRL TEXT NOT NULL,
    laserAP TEXT NOT NULL,
    laserCheck TEXT NOT NULL,
    xa array NOT NULL,
    ya array NOT NULL,
    doseArray array NOT NULL,
    calculated INTEGER NOT NULL,
    excluded INTEGER NOT NULL,
    energies TEXT,
    fieldSizeX REAL,
    fieldSizeY REAL,
    leftPenumbra REAL,
    rightPenumbra REAL,
    upPenumbra REAL,
    downPenumbra REAL,
    flatnessX REAL,
    flatnessY REAL,
    symmetryX REAL,
    symmetryY REAL,
    outputPass TEXT,
    energyPass TEXT,
    spotPositionXPass TEXT,
    spotPositionYPass TEXT,
    spotPositionCheck TEXT,
    spotSizeXPass TEXT,
    spotSizeYPass TEXT,
    spotSizeCheck TEXT,
    background REAL,
    output REAL,
    energy REAL,
    spotXOff TEXT,
    spotYOff TEXT,
    spotXSigma TEXT,
    spotYSigma TEXT,
    note TEXT
);

